config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  get 'pages/location'

  resources :dogs
  resources :owners

  root 'pages#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :dogs

  # Normalizes the attribute itself before validation
  phony_normalize :phone, default_country_code: 'US'

  validates :first_name, :last_name, presence: true
  validates_plausible_phone :phone, normalized_country_code: 'US', presence: true

  def last_comma_first
    "#{last_name}, #{first_name}"
  end

end

# == Schema Information
#
# Table name: owners
#
#  id          :integer          not null, primary key
#  first_name  :string
#  last_name   :string
#  phone       :string
#  evac_waiver :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /owners
  # GET /owners.json
  def index
    if params[:search_owner]
      @owners = Owner.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:search_owner]}%", "%#{params[:search_owner]}%")
      if @owners.empty?
        flash[:alert] = "Sorry, not results found"
        @owners = Owner.all
      end
    else
      @owners = Owner.all
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :phone, :evac_waiver)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control", placeholder: 'Jane' %>
  </div>
  <div class="field form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control", placeholder: 'Smith' %>
  </div>
  <div class="field form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: '504-555-1212' %>
  </div>
  <div class="field form-group">
    <div class="checkbox-inline">
      <%= f.check_box :evac_waiver %>
      <%= f.label :evac_waiver, "Evacuation Waiver signed and accepted" %><br>
    </div>
  </div>
  <%# TODO: Fix button alignment or spacing %>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Editing Owner</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @owner, class: "btn btn-default"  %> |
    <%= link_to 'Back', owners_path, class: "btn btn-default"  %>

  </div>
</div>

app/views/owners/index.html.erb
<h1>Doggy Parents</h1>
<!-- Owner search box -->
<%= form_tag("/owners", method: :get, role: 'search', class: 'form-inline') do %>
  <div class="form-group">
    <%= text_field_tag(:search_owner, nil, placeholder: 'Jane', class: 'form-control input-sm') %>
  </div>
  <%= submit_tag('Search', class: 'btn btn-default btn-sm') %>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th class="text-center">Evacuation Waiver</th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.phone.phony_formatted(format: :international, spaces: ' ') %></td>
        <td class="text-success text-center"><%= fa_icon('check', class: 'fa-2x') if owner.evac_waiver %></td>

        <td class="text-center">
          <div class="btn-group">
            <%= link_to fa_icon('eye', text: 'Show'), owner, class: 'btn btn-default btn-sm' %>
            <%= link_to fa_icon('pencil', text: 'Edit'), edit_owner_path(owner), class: 'btn btn-default btn-sm' %>
            <%= link_to fa_icon('trash', text: 'Destroy'), owner, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to fa_icon('plus', text: 'Add Owner'), new_owner_path, class: "btn btn-default" %>

app/views/owners/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>New Owner</h1>

    <%= render 'form' %>

    <%= link_to 'Back', owners_path, class: "btn btn-default" %>
  </div>
</div>

app/views/owners/show.html.erb
<h2><%= @owner.first_name %> <%= @owner.last_name %></h2>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone.phony_formatted(format: :international, spaces: ' ') %>
</p>

<p>
  <strong>Evac waiver:</strong>
  <%= @owner.evac_waiver %>
</p>

<h3><%= @owner.first_name %>'s Furry Friends:</h3>
<div class="row">
  <% @owner.dogs.each do |dog| %>
    <div class="col-xs-6 col-sm-4 col-md-3">

      <div class="panel <%= dog.in_daycare ? 'panel-success' : 'panel-default'  %>">
        <div class="panel-heading">
          <h3 class="panel-title"><%= dog.name %> <%= dog.owner.try(:last_name) %></h3>
        </div>
        <div class="panel-body">
          <%= image_tag dog.avatar.url(:medium), class: 'img-rounded img-responsive' %>
          <p>
            <%= link_to fa_icon('eye', text: 'Show'), dog, class: 'btn btn-default btn-xs' %>
            <%= link_to fa_icon('pencil', text: 'Edit'), edit_dog_path(dog), class: 'btn btn-default btn-xs' %>
          </p>
        </div>
      </div>

    </div>
  <% end %>
</div>

<p>
  <%= link_to fa_icon('pencil', text: 'Edit Owner'), edit_owner_path(@owner), class: 'btn btn-primary' %>
  <%= link_to fa_icon('list', text: 'All Owners'), owners_path, class: 'btn btn-default' %>
</p>