config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  get 'pages/location'

  resources :dogs
  resources :owners

  root 'pages#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :breed
  belongs_to :owner

  validates :name, :breed_id, :owner_id, :dob, presence: true

  has_attached_file :avatar, styles: {
    medium: "300x300#",
    thumb: "100x100#"
    }, default_url: ":style_missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_attachment_size :avatar, :less_than => 3.megabytes,
    :unless => Proc.new {|m| m[:avatar_file_name].blank?}
end

# == Schema Information
#
# Table name: dogs
#
#  id                  :integer          not null, primary key
#  name                :string
#  breed_id            :integer
#  dob                 :date
#  owner_id            :integer
#  medical_conditions  :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  in_daycare          :boolean
#
# Indexes
#
#  index_dogs_on_breed_id  (breed_id)
#  index_dogs_on_owner_id  (owner_id)
#

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :all_breeds, only: [:new, :edit, :index, :update, :create]
  before_action :all_owners, only: [:new, :edit, :update, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /dogs
  # GET /dogs.json
  def index
    # if we have the parameter, then only give me dogs that match
    if params[:search]
      @dogs = Dog.where("name LIKE ?", "%#{params[:search]}%")
      # if no dogs returns, give error message and list all dogs
      if @dogs.size.zero?
        flash[:alert] = "Sorry, no result found."
        @dogs = Dog.all
      end
    elsif params[:breed_id]
      @dogs = Dog.where(breed_id: params[:breed_id])
    # else, give me all dogs
    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dogs_path, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def all_breeds
      @breeds = Breed.order("breed_name")
    end

    def all_owners
      @owners = Owner.order("last_name")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed_id, :dob, :owner_id, :medical_conditions, :avatar, :in_daycare)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :breed_id %><br>
    <%= f.collection_select :breed_id, @breeds, :id, :breed_name, {prompt: "Select breed"}, {class: "form-control"} %>
  </div>
  <%# TODO:  Make years go further back and end at current year  %>
  <div class="field form-group">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field form-group">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, @owners, :id, :last_comma_first, {prompt: 'Select owner'}, {class: "form-control"} %>
  </div>
  <div class="field form-group">
    <%= f.label :medical_conditions %><br>
    <%= f.text_field :medical_conditions, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field form-group">
    <div class="checkbox-inline">
      <%= f.check_box :in_daycare %>
      <%= f.label :in_daycare, "Currently in daycare" %><br>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Editing Dog</h1>

    <%= render 'form' %>

    <br>
    <%= link_to fa_icon('eye', text: 'Show Dog'), @dog, class: 'btn btn-default' %>
    <%= link_to fa_icon('list', text: 'All Dogs'), dogs_path, class: 'btn btn-default' %>
    <%= link_to fa_icon('trash', text: 'Delete'), @dog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="row">
  <div class="col-sm-12">
  <h1>Our Furry Friends</h1>
    <!-- Dog search box -->
    <%= form_tag("/dogs", method: :get, role: 'search', class: 'form-inline') do %>
      <div class="form-group">
        <%= text_field_tag(:search, nil, placeholder: 'Fido', class: 'form-control input-sm') %>
      </div>
      <%= submit_tag('Search', class: 'btn btn-default btn-sm') %>
      <%= link_to fa_icon('plus', text: 'Add Dog'), new_dog_path, class: "btn btn-success btn-sm" %>
    <% end %>

    <br>
    <!-- Loop to generate breed filter buttons -->
    <p>
      <%= link_to "All", dogs_path, class: 'btn btn-default btn-xs' %>
      <% @breeds.each do |breed| %>
        <a href="?breed_id=<%= breed.id %>" class="btn btn-default btn-xs"><%= breed.breed_name %></a>
      <% end %>
    </p>
  </div>
</div>

<div class="row">

  <% @dogs.each do |dog| %>

    <div class="col-xs-6 col-sm-4 col-md-3">

      <div class="panel <%= dog.in_daycare ? 'panel-success' : 'panel-default'  %>">
        <div class="panel-heading">
          <h3 class="panel-title"><%= dog.name %> <%= dog.owner.try(:last_name) %></h3>
        </div>
        <div class="panel-body">
          <%= link_to dog do %>
            <%= image_tag dog.avatar.url(:medium), class: 'img-rounded img-responsive' %>
          <% end %>
          <p>
            <!-- Check in/out buttons -->
            <%= form_for(dog, url: dog_path(dog), html: {class: 'form-inline'}) do |f| %>
              <% if dog.in_daycare %>
                <%= f.hidden_field :in_daycare, value: false %>
                <%= f.submit "Check Out", class: 'btn btn-success btn-xs' %>
              <% else %>
                <%= f.hidden_field :in_daycare, value: true %>
                <%= f.submit "Check In", class: 'btn btn-default btn-xs' %>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>

    </div>

  <% end %>
</div>

app/views/dogs/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>New Dog</h1>

    <%= render 'form' %>

    <%= link_to 'Back', dogs_path %>
  </div>
</div>

app/views/dogs/show.html.erb
<h1>Dog Details</h1>

<div class="row">
  <div class="col-sm-4">
    <%= image_tag @dog.avatar.url(:medium), class: "img-responsive img-rounded" %>
  </div>
  <div class="col-sm-8">
    <h3><%= @dog.name + " " + @dog.owner.last_name %></h3>

    <p>
      <strong>Owner:</strong>
      <%= link_to "#{@dog.owner.first_name} #{@dog.owner.last_name}", @dog.owner %>
    </p>

    <p>
      <strong>Breed:</strong>
      <%= @dog.breed.breed_name %>
    </p>

    <p>
      <strong>Dob:</strong>
      <%= @dog.dob.stamp("March 1, 1999") %>
    </p>

    <p>
      <strong>Medical conditions:</strong>
      <%= @dog.medical_conditions ? "(none listed)" : @dog.medical_conditions  %>
    </p>

    <p>
      <strong>In Daycare:</strong>
      <%= @dog.in_daycare ? fa_icon('check', class: 'fa-2x') : fa_icon('times', class: 'fa-2x') %>
    </p>

    <p>
      <%= link_to fa_icon('pencil', text: 'Edit Dog'), edit_dog_path(@dog), class: 'btn btn-primary' %>
      <%= link_to fa_icon('grid', text: 'All Dogs'), dogs_path, class: 'btn btn-default' %>
    </p>
  </div>
</div>