config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  get 'pages/location'

  resources :dogs
  resources :owners

  root 'pages#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Muzzle Toff', root_url, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Owners", owners_url %></li>
      <li><%= link_to "Dogs", dogs_url %></li>
      <li><%= link_to fa_icon('map-marker', text: "Location"), pages_location_url %></li>
    </ul>

    <!-- User Links -->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to fa_icon('gear', text: 'Account'), edit_user_registration_path %></li>
        <li><%= link_to(fa_icon('sign-out', text: 'Logout'), destroy_user_session_path, :method => :delete) %></li>
      <% else %>
        <li><%= link_to(fa_icon('sign-in', text: 'Login'), new_user_session_path)  %></li>
        <li><%= link_to fa_icon('user-plus', text: 'Sign up'), new_user_registration_path %></li>
      <% end %>
    </ul>


  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DoggyDaycare</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.3.5/journal/bootstrap.min.css">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>